#! /bin/sh
cat << EOF
/* This file is automatically generated! Do not modify! */
#ifdef HAVE_CONFIG_H
# include <config.h>
#endif
#include <stdbool.h>
#include <sys/types.h>
#include <sys/socket.h>
#include "stun-msg.h"

#include <assert.h>

bool stun_is_unknown (uint16_t type)
{
	assert (!stun_optional (type));

	switch (type)
	{
EOF

sed -n -e 's/\s*\(STUN_[A-Z_]*\)=0x[0-7][0-9A-F]\{3\},/\t\tcase \1:/p'

cat << EOF
			return false;

		default:
			return true;
	}
}
EOF

